// Generated by scripts/dev/capture-okx-demo-evidence.ts — recorded, not live.
// Show only under a "Recorded demonstration — captured at …" label.
import type { OkxDemoCheckResult, OkxDemoStatus } from "./okx-demo-identity.ts";

export const OKX_DEMO_RECORDED: {
  capturedAt: string;
  revision: string;
  status: OkxDemoStatus;
  cases: { endpoint: OkxDemoCheckResult; failure: OkxDemoCheckResult; agent: OkxDemoCheckResult };
} = {
  "capturedAt": "2026-10-04T08:36:50.088Z",
  "revision": "c837e90",
  "status": {
    "ok": true,
    "source": "live",
    "endpointUrl": "https://kind-meitner-production.up.railway.app/api/okx/free-mcp",
    "checkedAt": "2026-10-04T08:36:47.509Z",
    "latencyMs": 881,
    "protocolVersion": "2024-11-05",
    "serverName": "kind-meitner-free-okx-ai",
    "tools": [
      "list_okx_ai_use_cases",
      "get_free_a2mcp_launch_checklist",
      "scan_free_mcp_readiness",
      "get_asp_trust_card",
      "query_market_benchmarks",
      "get_asp_reputation",
      "get_trending_asps"
    ],
    "demoToolsAvailable": true,
    "safeMessage": "Connected · 7 tools"
  },
  "cases": {
    "endpoint": {
      "ok": true,
      "source": "live",
      "tool": "scan_free_mcp_readiness",
      "requestId": "fea17a6c-48c8-430f-85f1-e31654458d1b",
      "startedAt": "2026-10-04T08:36:48.391Z",
      "latencyMs": 395,
      "arguments": {
        "endpointUrl": "https://kind-meitner-production.up.railway.app/api/okx/free-mcp"
      },
      "endpointUrl": "https://kind-meitner-production.up.railway.app/api/okx/free-mcp",
      "envelope": {
        "resource": {
          "access": "free",
          "paymentRequired": false,
          "walletRequired": false,
          "mainnet": false,
          "provenance": "kind-meitner live HTTPS probes + public listing pitfalls"
        },
        "data": {
          "endpointUrl": "https://kind-meitner-production.up.railway.app/api/okx/free-mcp",
          "agentId": null,
          "verdict": "PASS",
          "score": 100,
          "checks": [
            {
              "id": "https_scheme",
              "status": "pass",
              "detail": "https"
            },
            {
              "id": "host_pitfall_vercel",
              "status": "pass",
              "detail": "host=kind-meitner-production.up.railway.app"
            },
            {
              "id": "tools_list_http",
              "status": "pass",
              "detail": "status=200 latencyMs=52"
            },
            {
              "id": "tools_list_shape",
              "status": "pass",
              "detail": "7 tools"
            },
            {
              "id": "no_accidental_402",
              "status": "pass",
              "detail": "no 402"
            },
            {
              "id": "initialize_soft",
              "status": "pass",
              "detail": "status=200"
            }
          ],
          "remediation": [],
          "raw": {
            "httpStatus": 200,
            "toolNames": [
              "list_okx_ai_use_cases",
              "get_free_a2mcp_launch_checklist",
              "scan_free_mcp_readiness",
              "get_asp_trust_card",
              "query_market_benchmarks",
              "get_asp_reputation",
              "get_trending_asps"
            ],
            "truncatedNotes": ""
          },
          "receipt": {
            "schema": "kindmeitner.readiness.v1",
            "id": "rcpt-90947996c1b31418",
            "evidenceHash": "0x90947996c1b31418ce90e74a72372fc0648a897b61078b03d2127f1ad3963d37"
          }
        }
      }
    },
    "failure": {
      "ok": true,
      "source": "live",
      "tool": "scan_free_mcp_readiness",
      "requestId": "711db99e-caeb-49ad-ab5c-4463deb0ab84",
      "startedAt": "2026-10-04T08:36:48.786Z",
      "latencyMs": 239,
      "arguments": {
        "endpointUrl": "https://127.0.0.1/mcp"
      },
      "endpointUrl": "https://kind-meitner-production.up.railway.app/api/okx/free-mcp",
      "envelope": {
        "resource": {
          "access": "free",
          "paymentRequired": false,
          "walletRequired": false,
          "mainnet": false,
          "provenance": "kind-meitner live HTTPS probes + public listing pitfalls"
        },
        "data": {
          "endpointUrl": "https://127.0.0.1/mcp",
          "agentId": null,
          "verdict": "FAIL",
          "score": 33,
          "checks": [
            {
              "id": "https_scheme",
              "status": "pass",
              "detail": "https"
            },
            {
              "id": "host_pitfall_vercel",
              "status": "pass",
              "detail": "host=127.0.0.1"
            },
            {
              "id": "tools_list_http",
              "status": "fail",
              "detail": "private or loopback target blocked"
            },
            {
              "id": "tools_list_shape",
              "status": "warn",
              "detail": "not checked"
            },
            {
              "id": "no_accidental_402",
              "status": "warn",
              "detail": "not checked"
            },
            {
              "id": "initialize_soft",
              "status": "warn",
              "detail": "not checked"
            }
          ],
          "remediation": [
            "Use a public HTTPS endpoint; private, loopback, and link-local targets cannot be scanned."
          ],
          "raw": {
            "httpStatus": null,
            "toolNames": [],
            "truncatedNotes": ""
          },
          "receipt": {
            "schema": "kindmeitner.readiness.v1",
            "id": "rcpt-b08cef5270a9a837",
            "evidenceHash": "0xb08cef5270a9a837b0a1d59d08141e63969e35ea214a31f1b845e0bb844ada12"
          }
        }
      }
    },
    "agent": {
      "ok": true,
      "source": "live",
      "tool": "check_agent_listing_and_connection",
      "requestId": "d2d152c2-bdf2-4028-b785-fff45ccdd811",
      "startedAt": "2026-10-04T08:36:49.025Z",
      "latencyMs": 1031,
      "arguments": {
        "agentId": "13851",
        "endpointUrl": "https://kind-meitner-production.up.railway.app/api/okx/free-mcp"
      },
      "endpointUrl": "https://kind-meitner-production.up.railway.app/api/okx/free-mcp",
      "envelope": {
        "resource": {
          "access": "free",
          "paymentRequired": false,
          "walletRequired": false,
          "mainnet": false,
          "provenance": "okx.ai listing page; not an OKX endorsement"
        },
        "data": {
          "agentId": "13851",
          "agentName": "Kind Meitner Markets",
          "description": "Free read-only tools that verify if a public HTTPS endpoint is ready for listing and if an agent is safe to call before spending. No wallet, payment, or mainnet settlement required. Results come from local probes, not live marketplace prices or an OKX endorsement.",
          "avatarUrl": "https://static.okx.com/cdn/web3/wallet/marketplace/headimages/agent/avatar/8519bf07-9284-444a-90e4-653cb6531aac.png",
          "listingStatus": "found",
          "connectionStatus": "passed",
          "endpointAssociation": "verified",
          "endpointAssociationDetail": "Declared in listing",
          "summary": "Listing found — Kind Meitner Markets. Public listing information was retrieved. Service connection check passed (declared in listing).",
          "listing": {
            "agentId": "13851",
            "name": "Kind Meitner Markets",
            "description": "Free read-only tools that verify if a public HTTPS endpoint is ready for listing and if an agent is safe to call before spending. No wallet, payment, or mainnet settlement required. Results come from local probes, not live marketplace prices or an OKX endorsement.",
            "listingUrl": "https://www.okx.ai/agents/13851",
            "avatarUrl": "https://static.okx.com/cdn/web3/wallet/marketplace/headimages/agent/avatar/8519bf07-9284-444a-90e4-653cb6531aac.png",
            "services": [
              {
                "serviceId": 40840,
                "name": "Free Readiness Trust",
                "description": "Checks Free MCP listing readiness and pre-spend trust for OKX agents.",
                "price": "0",
                "symbol": "USDT",
                "serviceType": "A2MCP",
                "endpoint": "https://kind-meitner-production.up.railway.app/api/okx/free-mcp"
              }
            ],
            "fetchTime": "2026-10-04T08:36:49.025Z",
            "source": "okx.ai listing page"
          },
          "services": [
            {
              "serviceId": 40840,
              "name": "Free Readiness Trust",
              "description": "Checks Free MCP listing readiness and pre-spend trust for OKX agents.\nendpointUrl (string, required): public HTTPS Free MCP URL; agentId (string, optional): marketplace agent ID for trust check\nPOST\ncurl -X POST https://kind-meitner-production.up.railway.app/api/okx/free-mcp -H 'content-type: application/json' -d '{\"jsonrpc\":\"2.0\",\"id\":\"1\",\"method\":\"tools/list\"}'",
              "price": "0"
            }
          ],
          "checksPerformed": [
            {
              "id": "listing_page",
              "status": "pass",
              "label": "Listing page",
              "detail": "Public listing information was retrieved."
            },
            {
              "id": "service_connection",
              "status": "pass",
              "label": "Service connection",
              "detail": "Protocol check passed · 7 tool(s) discovered."
            }
          ],
          "limitations": [
            "Service delivery, output quality and payment outcomes were not assessed.",
            "This check is free and read-only. The target service may have separate fees or access requirements."
          ],
          "nextActions": [
            "Connection checks passed. Individual tool execution and delivery quality were not tested."
          ],
          "signals": [
            {
              "id": "listing_page",
              "status": "pass",
              "label": "Listing page",
              "detail": "Public listing information was retrieved."
            },
            {
              "id": "service_connection",
              "status": "pass",
              "label": "Service connection",
              "detail": "Protocol check passed · 7 tool(s) discovered."
            }
          ],
          "notChecked": [
            "Service delivery, output quality and payment outcomes were not assessed.",
            "Historical transaction and settlement volume",
            "OKX official endorsement"
          ],
          "remediation": [],
          "safeNextStep": "Connection checks passed. Individual tool execution and delivery quality were not tested.",
          "decision": "GO"
        }
      }
    }
  }
};
