// Captures the three Dev Day demo cases from the live service through the
// same client the app uses, and writes them as clearly recorded evidence.
//   node --experimental-strip-types scripts/dev/capture-okx-demo-evidence.ts
// Read-only: three tools/call requests to our own endpoint; the failure case
// targets loopback, which the service refuses without any network probe.
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { OKX_DEMO_CONTROLLED_FAILURE_URL, OKX_DEMO_IDENTITY } from "../../shared/okx-demo-identity.ts";
import { demoStatus, runDemoCheck } from "../../server/okx/demo-client.ts";

const status = await demoStatus();
if (!status.ok) throw new Error(`live service not ready: ${status.safeMessage}`);
const cases = {
  endpoint: await runDemoCheck({ kind: "endpoint", endpointUrl: OKX_DEMO_IDENTITY.endpointUrl }),
  failure: await runDemoCheck({ kind: "endpoint", endpointUrl: OKX_DEMO_CONTROLLED_FAILURE_URL }),
  agent: await runDemoCheck({ kind: "agent", agentId: OKX_DEMO_IDENTITY.agentId, endpointUrl: OKX_DEMO_IDENTITY.endpointUrl }),
};
for (const [name, result] of Object.entries(cases)) {
  if (!result.ok) throw new Error(`${name}: ${result.status} ${result.safeMessage}`);
}
const revision = execFileSync("git", ["rev-parse", "--short", "HEAD"], { encoding: "utf8" }).trim();
const recorded = { capturedAt: new Date().toISOString(), revision, status, cases };
writeFileSync(
  new URL("../../shared/okx-demo-recorded.ts", import.meta.url),
  `// Generated by scripts/dev/capture-okx-demo-evidence.ts — recorded, not live.\n` +
    `// Show only under a "Recorded demonstration — captured at …" label.\n` +
    `import type { OkxDemoCheckResult, OkxDemoStatus } from "./okx-demo-identity.ts";\n\n` +
    `export const OKX_DEMO_RECORDED: {\n  capturedAt: string;\n  revision: string;\n  status: OkxDemoStatus;\n  cases: { endpoint: OkxDemoCheckResult; failure: OkxDemoCheckResult; agent: OkxDemoCheckResult };\n} = ${JSON.stringify(recorded, null, 2)};\n`,
);
console.log(JSON.stringify({ capturedAt: recorded.capturedAt, revision, status: status.safeMessage, verdicts: Object.fromEntries(Object.entries(cases).map(([k, r]) => [k, r.ok ? (r.envelope.data.verdict ?? r.envelope.data.decision) : r.status])) }, null, 2));
